add missing include for shared_ptr
This fixes
  error: 'shared_ptr' in namespace 'std' does not name a type
on Linux, and should be a noop on other platforms.